services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: alumni_mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=root@123
    networks:
      - app-network

  app:
    build: .
    container_name: alumnidbms_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db
    env_file:
      - .env 
    environment:
      - DB_HOST=db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge